name: lplr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - accelerate=0.18.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py310h1fa729e_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=ha770c72_13_cpu
  - astroid=2.15.4=py310hff52083_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - autoflake=1.7.5=pyhd8ed1ab_0
  - aws-c-auth=0.6.26=hf365957_1
  - aws-c-cal=0.5.21=h48707d8_2
  - aws-c-common=0.8.14=h0b41bf4_0
  - aws-c-compression=0.2.16=h03acc5a_5
  - aws-c-event-stream=0.2.20=h00877a2_4
  - aws-c-http=0.7.6=hf342b9f_0
  - aws-c-io=0.13.19=h5b20300_3
  - aws-c-mqtt=0.8.6=hc4349f7_12
  - aws-c-s3=0.2.7=h909e904_1
  - aws-c-sdkutils=0.1.8=h03acc5a_0
  - aws-checksums=0.1.14=h03acc5a_5
  - aws-crt-cpp=0.19.8=hf7fbfca_12
  - aws-sdk-cpp=1.10.57=h17c43bd_8
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bandit=1.7.5=py310hff52083_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=23.3.0=py310hff52083_0
  - blas=2.112=mkl
  - blas-devel=3.9.0=12_linux64_mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - chardet=4.0.0=py310hff52083_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - conda=23.3.1=py310hff52083_0
  - conda-build=3.24.0=py310hff52083_1
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - contourpy=1.0.7=py310hdf3cbec_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - cryptography=40.0.2=py310h34c0648_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.4.2=h7a5bcfd_11
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataproperty=0.55.0=pyhd8ed1ab_0
  - datasets=2.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py310heca2aa9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - docker-pycreds=0.4.0=py_0
  - dynaconf=3.1.12=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - evaluate=0.2.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - faiss-gpu=1.7.4=py3.10_hc0239a3_0_cuda11.4
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.11.0=pyhd8ed1ab_0
  - fire=0.5.0=pyhd8ed1ab_0
  - flake8=6.0.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - fonttools=4.39.3=py310h1fa729e_0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.3.3=py310h5764c6d_0
  - fsspec=2023.4.0=pyh1a96a4e_0
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glob2=0.7=py_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - huggingface_hub=0.13.4=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.4.1=pyha770c72_0
  - importlib_metadata=6.4.1=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipdb=0.13.13=pyhd8ed1ab_0
  - ipykernel=6.22.0=pyh210e3f2_0
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipython=8.12.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonlines=3.1.0=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hff52083_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=3.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lazy-object-proxy=1.9.0=py310h1fa729e_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.0=cxx17_hcb278e6_1
  - libarchive=3.6.2=h3d51595_0
  - libarrow=11.0.0=h93537a5_13_cpu
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=12_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurl=8.0.1=h588be90_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libfaiss=1.7.4=h13c3c6d_0_cuda11.4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libgoogle-cloud=2.8.0=h0bc5f78_1
  - libgrpc=1.52.1=hcf146ea_1
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - liblief=0.12.3=h27087fc_0
  - libmamba=1.4.2=hcea66bb_0
  - libmambapy=1.4.2=py310h1428755_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnuma=2.0.16=h0b41bf4_1
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=h3eb15da_0
  - libsentencepiece=0.1.97=h47aad16_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.23=h3eb15da_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libthrift=0.18.1=h5e4af38_0
  - libtiff=4.5.0=h6adf6a1_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.4=hfdac1af_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.1=h417c0b6_0
  - loguru=0.7.0=py310hff52083_0
  - lxml=4.9.2=py310hbdc0903_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.4.2=py310h51d5547_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mbstrdecoder=1.1.2=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl-devel=2021.4.0=ha770c72_730
  - mkl-include=2021.4.0=h8d4b97c_729
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgfy=0.2.0=pyhd8ed1ab_0
  - multidict=6.0.4=py310h1fa729e_0
  - multiprocess=0.70.14=py310h5764c6d_3
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.2.0=py310h1fa729e_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - natsort=8.3.1=pyhd8ed1ab_0
  - nbclassic=0.5.5=pyh8b2e9e2_0
  - nbclient=0.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.3.1=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nbstripout=0.6.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - nltk=3.8.1=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numexpr=2.7.3=py310hb5077e9_1
  - numpy=1.24.2=py310h8deb116_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openai=0.27.6=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openpyxl=3.1.2=py310h2372a71_0
  - openssl=3.1.0=hd590300_3
  - orc=1.8.3=hfdbbad2_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.0=py310h9b08913_0
  - pandas-stubs=2.0.1.230501=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pathvalidate=2.5.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pbr=5.11.1=pyhd8ed1ab_0
  - peft=0.2.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h023d228_1
  - pip=23.1=pyhd8ed1ab_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pooch=1.7.0=pyha770c72_3
  - portalocker=2.7.0=py310hff52083_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=5.9.5=py310h1fa729e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.12.3=py310hd8f1fbe_0
  - pyarrow=11.0.0=py310h633f555_13_cpu
  - pybind11=2.10.4=py310hdf3cbec_0
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.10.4=py310hdf3cbec_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycosat=0.6.4=py310h5764c6d_1
  - pycountry=22.3.5=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.15.0=pyhd8ed1ab_0
  - pylint=2.17.4=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h1fa729e_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytablewriter=0.64.2=pyhd8ed1ab_0
  - python=3.10.10=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py310hff52083_2
  - python-slugify=8.0.1=pyhd8ed1ab_1
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.2.0=py310h1fa729e_0
  - python_abi=3.10=3_cp310
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytorch=2.0.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_3
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_5
  - pyzmq=25.0.2=py310h059b190_0
  - ratelimit=2.2.1=pyhd8ed1ab_0
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - re2=2023.02.02=hcb278e6_0
  - readline=8.2=h8228510_1
  - regex=2023.3.23=py310h1fa729e_0
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.28.2=pyhd8ed1ab_1
  - responses=0.18.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.3.4=pyhd8ed1ab_0
  - ripgrep=13.0.0=h2f28480_2
  - rope=1.7.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h1fa729e_3
  - ruamel.yaml.clib=0.2.7=py310h1fa729e_1
  - ruff=0.0.265=py310h3d77a66_0
  - s2n=1.3.41=h3358134_0
  - sacrebleu=1.5.0=pyh44b312d_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py310h41b6a48_1
  - scipy=1.10.1=py310h8deb116_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentence-transformers=2.2.2=pyhd8ed1ab_0
  - sentencepiece=0.1.97=hff52083_1
  - sentencepiece-python=0.1.97=py310h385333e_1
  - sentencepiece-spm=0.1.97=h47aad16_1
  - sentry-sdk=1.21.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h5764c6d_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlitedict=2.0.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h278f3c1_1
  - stevedore=5.0.0=pyhd8ed1ab_0
  - sympy=1.11.1=pypyh9d50eac_103
  - tabledata=1.3.1=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tcolorpy=0.1.2=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - text-unidecode=1.3=py_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - timm=0.6.13=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tokenizers=0.13.3=py310he1f1126_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=2.0.0=py310_cu117
  - torchtriton=2.0.0=py310
  - torchvision=0.15.0=py310_cu117
  - tornado=6.2=py310h5764c6d_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - transformers=4.28.1=pyhd8ed1ab_0
  - typepy=1.3.0=pyhd8ed1ab_0
  - types-pytz=2023.3.0.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.14.0=h8c404fb_1
  - unicodedata2=15.0.0=py310h5764c6d_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wandb=0.15.2=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h1fa729e_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xxhash=0.8.1=h0b41bf4_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_2
  - yapf=0.33.0=pyhd8ed1ab_1
  - yarl=1.8.2=py310h5764c6d_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py310hdeb6495_1
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - absl-py==1.4.0
      - bitsandbytes==0.38.1
      - fairscale==0.4.13
      - fqdn==1.5.1
      - intel-openmp==2023.1.0
      - isoduration==20.11.0
      - jupyterlab-code-formatter==1.6.1
      - mkl==2023.1.0
      - mteb==1.0.2
      - rouge-score==0.1.2
      - tbb==2021.9.0
      - uri-template==1.2.0
      - webcolors==1.13
prefix: /home/rsaha/.pyenv/versions/miniforge3-latest/envs/lplr
